dest: "./backups"
printDumpLogs: false

# pg_dump
dump:
  enable: true
  # how many "pg_dump" execs may be run at once, default=2
  maxConcurrency: 8
  databases:
    - host: localhost
      port: 5432
      username: postgres
      password: postgres
      dbname: bookstore
      opts:
        connect_timeout: "5"
        sslmode: "disable"
      schemas: [ ]
      excludeSchemas: [ ]
      tables: [ ]
      excludeTables: [ ]
      # default=4
      jobs: 8

    - host: 10.40.240.189
      port: 5432
      username: postgres
      password: postgres
      dbname: keycloak_base

    - host: 10.40.240.165
      port: 30201
      username: postgres
      password: postgres
      dbname: vault

# pg_basebackup
base:
  enable: false
  compress: true
  # how many "pg_basebackup" execs may be run at once, default=2
  maxConcurrency: 2
  clusters:
    - host: localhost
      port: 5432
      username: postgres
      password: postgres
      opts:
        connect_timeout: "5"
        sslmode: "disable"

retention:
  enable: true
  period: 1m
  keepLast: 1

logger:
  # text/json
  format: text
  # debug info warn error
  level: debug
