dest: "./backups"
logDir: "" # /var/log/gopgdump
printDumpLogs: false

# pg_dump
dump:
  enable: true
  # how many "pg_dump" execs may be run at once, default=2
  maxConcurrency: 8
  databases:
    - host: localhost
      port: 5432
      username: backup
      password: ${PASS1}
      dbname: bookstore
      opts:
        connect_timeout: "5"
        sslmode: "disable"
      schemas: [ ]
      excludeSchemas: [ ]
      tables: [ ]
      excludeTables: [ ]
      # default=4
      jobs: 8
      execs:
        # example: /usr/lib/postgresql/17/bin/pg_dump
        pg_dump: ""

    - host: 10.40.240.189
      port: 5432
      username: postgres
      password: postgres
      dbname: keycloak_base
      execs:
        pg_dump: "C:\\Program Files\\PostgreSQL\\17\\bin\\pg_dump.exe"

    - host: 10.40.240.165
      port: 30201
      username: postgres
      password: postgres
      dbname: vault

# pg_basebackup
base:
  enable: true
  compress: true
  # how many "pg_basebackup" execs may be run at once, default=2
  maxConcurrency: 2
  clusters:
    - host: localhost
      port: 5432
      username: postgres
      password: postgres
      opts:
        connect_timeout: "5"
        sslmode: "disable"
      execs:
        pg_basebackup: ""     # example: /usr/lib/postgresql/17/bin/pg_basebackup
        pg_archivecleanup: "" # example: /usr/lib/postgresql/17/bin/pg_archivecleanup
        pg_verifybackup: ""   # example: /usr/lib/postgresql/17/bin/pg_verifybackup

retention:
  enable: true
  period: 1m
  keepLast: 1

logger:
  # text/json
  format: text
  # debug info warn error
  level: debug

notify:
  enable: true
  telegram:
    enable: true
    token: "${TG_BOT_TOKEN}"
    chatId: "${TG_BOT_CHAT_ID}"
