# connection settings (use PGPASSWORD env-var or .pgpass file to provide password)
host: 10.40.240.189
port: 5432
username: postgres

# optional: specify explicitly binaries path (otherwise $PATH variable is used to resolve binaries)
pgBinPath: ""

pgDump:
  ignoreDatabases:
    - logs_audit
    - archive_2020
  filters:
    iam_base:
      schemas: [ ]
      excludeSchemas: [ ]
      tables: [ ]
      excludeTables: [ ]
    bookstore: { }

