services:
  pg16:
    image: postgres:16.8-alpine
    container_name: pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "15432:5432"
    volumes:
      - pgdata16:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro

  pg17:
    image: postgres:17.4-alpine
    container_name: pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "15433:5432"
    volumes:
      - pgdata17:/var/lib/postgresql/data

volumes:
  pgdata16:
  pgdata17:
